/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.ncty.proyectofinal.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Fanoci
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAreas = new javax.swing.JMenu();
        menuAreaCirculo = new javax.swing.JMenuItem();
        menuAreaCuadrado = new javax.swing.JMenuItem();
        menuAreaRectangulo = new javax.swing.JMenuItem();
        menuAreaTriangulo = new javax.swing.JMenuItem();
        menuOtros = new javax.swing.JMenu();
        menuOtrosPromedio = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        menuSalirSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuAreas.setText("Areas");

        menuAreaCirculo.setText("Circulo");
        menuAreaCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaCirculoActionPerformed(evt);
            }
        });
        menuAreas.add(menuAreaCirculo);

        menuAreaCuadrado.setText("Cuadrado");
        menuAreaCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaCuadradoActionPerformed(evt);
            }
        });
        menuAreas.add(menuAreaCuadrado);

        menuAreaRectangulo.setText("Rectangulo");
        menuAreaRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaRectanguloActionPerformed(evt);
            }
        });
        menuAreas.add(menuAreaRectangulo);

        menuAreaTriangulo.setText("Triangulo");
        menuAreaTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAreaTrianguloActionPerformed(evt);
            }
        });
        menuAreas.add(menuAreaTriangulo);

        jMenuBar1.add(menuAreas);

        menuOtros.setText("Otros");

        menuOtrosPromedio.setText("Promedio");
        menuOtrosPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOtrosPromedioActionPerformed(evt);
            }
        });
        menuOtros.add(menuOtrosPromedio);

        jMenuBar1.add(menuOtros);

        menuSalir.setText("Salir");

        menuSalirSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuSalirSalir.setText("Salir");
        menuSalirSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirSalirActionPerformed(evt);
            }
        });
        menuSalir.add(menuSalirSalir);

        jMenuBar1.add(menuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAreaCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaCirculoActionPerformed
         JInternalFrame view = new Circulo();
       jDesktopPane1.add(view);
       view.setVisible(true);
    }//GEN-LAST:event_menuAreaCirculoActionPerformed

    private void menuAreaCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaCuadradoActionPerformed
          JInternalFrame view = new Cuadrado();
       jDesktopPane1.add(view);
       view.setVisible(true);
    }//GEN-LAST:event_menuAreaCuadradoActionPerformed

    private void menuSalirSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirSalirActionPerformed

    private void menuAreaRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaRectanguloActionPerformed
            JInternalFrame view = new Rectangulo();
       jDesktopPane1.add(view);
       view.setVisible(true);
    }//GEN-LAST:event_menuAreaRectanguloActionPerformed

    private void menuAreaTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAreaTrianguloActionPerformed
         JInternalFrame view = new Triangulo();
       jDesktopPane1.add(view);
       view.setVisible(true);
    }//GEN-LAST:event_menuAreaTrianguloActionPerformed

    private void menuOtrosPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOtrosPromedioActionPerformed
           JInternalFrame view = new Promedio();
       jDesktopPane1.add(view);
       view.setVisible(true);
    }//GEN-LAST:event_menuOtrosPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAreaCirculo;
    private javax.swing.JMenuItem menuAreaCuadrado;
    private javax.swing.JMenuItem menuAreaRectangulo;
    private javax.swing.JMenuItem menuAreaTriangulo;
    private javax.swing.JMenu menuAreas;
    private javax.swing.JMenu menuOtros;
    private javax.swing.JMenuItem menuOtrosPromedio;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem menuSalirSalir;
    // End of variables declaration//GEN-END:variables
}
