/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JFrame;

/**
 *
 * @author Jeremy
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        ConfiguracionMainView();
    }
    public void ConfiguracionMainView(){
        this.setSize(800,600);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuArchivoCerrar = new javax.swing.JMenuItem();
        menuFiguras = new javax.swing.JMenu();
        menuFigurasCilindro = new javax.swing.JMenuItem();
        menuFigurasEsfera = new javax.swing.JMenuItem();
        menuFigurasCono = new javax.swing.JMenuItem();
        menuFigurasCubo = new javax.swing.JMenuItem();
        menuFigurasParalelepipedo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULO DE FIGURAS");

        javax.swing.GroupLayout dpContenedorLayout = new javax.swing.GroupLayout(dpContenedor);
        dpContenedor.setLayout(dpContenedorLayout);
        dpContenedorLayout.setHorizontalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        dpContenedorLayout.setVerticalGroup(
            dpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivo");

        menuArchivoCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        menuArchivoCerrar.setText("Cerrar");
        menuArchivoCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuArchivoCerrarActionPerformed(evt);
            }
        });
        menuArchivo.add(menuArchivoCerrar);

        jMenuBar1.add(menuArchivo);

        menuFiguras.setText("Figuras Solidas");

        menuFigurasCilindro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        menuFigurasCilindro.setText("Cilindro");
        menuFigurasCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFigurasCilindroActionPerformed(evt);
            }
        });
        menuFiguras.add(menuFigurasCilindro);

        menuFigurasEsfera.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        menuFigurasEsfera.setText("Esfera");
        menuFigurasEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFigurasEsferaActionPerformed(evt);
            }
        });
        menuFiguras.add(menuFigurasEsfera);

        menuFigurasCono.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        menuFigurasCono.setText("Cono");
        menuFigurasCono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFigurasConoActionPerformed(evt);
            }
        });
        menuFiguras.add(menuFigurasCono);

        menuFigurasCubo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        menuFigurasCubo.setText("Cubo");
        menuFigurasCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFigurasCuboActionPerformed(evt);
            }
        });
        menuFiguras.add(menuFigurasCubo);

        menuFigurasParalelepipedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.ALT_MASK));
        menuFigurasParalelepipedo.setText("Paralelepipedo");
        menuFigurasParalelepipedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFigurasParalelepipedoActionPerformed(evt);
            }
        });
        menuFiguras.add(menuFigurasParalelepipedo);

        jMenuBar1.add(menuFiguras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuFigurasEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFigurasEsferaActionPerformed
        // TODO add your handling code here:
        Esfera esf=new Esfera();
        this.dpContenedor.add(esf);
        esf.show();
    }//GEN-LAST:event_menuFigurasEsferaActionPerformed

    private void menuFigurasConoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFigurasConoActionPerformed
        // TODO add your handling code here:
        Cono con=new Cono();
        this.dpContenedor.add(con);
        con.show();
    }//GEN-LAST:event_menuFigurasConoActionPerformed

    private void menuFigurasCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFigurasCuboActionPerformed
        // TODO add your handling code here:
        Cubo cub=new Cubo();
        this.dpContenedor.add(cub);
        cub.show();
    }//GEN-LAST:event_menuFigurasCuboActionPerformed

    private void menuFigurasCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFigurasCilindroActionPerformed
        // TODO add your handling code here:
        Cilindro cl=new Cilindro();
        this.dpContenedor.add(cl);
        cl.show();
    }//GEN-LAST:event_menuFigurasCilindroActionPerformed

    private void menuFigurasParalelepipedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFigurasParalelepipedoActionPerformed
        // TODO add your handling code here:
        Paralelepipedo paral=new Paralelepipedo();
        this.dpContenedor.add(paral);
        paral.show();
    }//GEN-LAST:event_menuFigurasParalelepipedoActionPerformed

    private void menuArchivoCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuArchivoCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuArchivoCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpContenedor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuArchivoCerrar;
    private javax.swing.JMenu menuFiguras;
    private javax.swing.JMenuItem menuFigurasCilindro;
    private javax.swing.JMenuItem menuFigurasCono;
    private javax.swing.JMenuItem menuFigurasCubo;
    private javax.swing.JMenuItem menuFigurasEsfera;
    private javax.swing.JMenuItem menuFigurasParalelepipedo;
    // End of variables declaration//GEN-END:variables
    
    
    
    
}
